### ISSUE TITLE
zap payment link

### ISSUE THREAD

**Issue by djpnewton** [zap-me/zap_bill_payment#11]
We need to show a zap link/url below the QR code.

This is so that mobile browsers can call the wallet app or desktop apps can be communicated with.

Reuse the same data in the QR code and make a link like: `<a href="{QR_CODE_DATA}">...`

**Comment by eoliveros** [comment]
I've decided to use the URL instead of creating QR_CODE_DATA and below is the image i'm getting:
![image](https://user-images.githubusercontent.com/47799652/88606662-5caff880-d0d1-11ea-8b80-52afb41a091a.png)


and below is what shows when i hover over the "Click this link":
![image](https://user-images.githubusercontent.com/47799652/88606751-9f71d080-d0d1-11ea-892d-07050de125a2.png)

**Comment by djpnewton** [comment]
ok looks fine

**Comment by djpnewton** [comment]
I need a PR to test

**Comment by eoliveros** [comment]
just tested after pulling master and editing. The result from previous entry is the same with different values. So test from my end appears to be successful.

**Comment by djpnewton** [comment]
merged PR, can you test the link from mobile browser on http://zap-bill-payment.herokuapp.com/utilities

**Comment by eoliveros** [comment]
can get to the site from testphone. 
The rendering doesn't look nice though.

The result is below:
![image](https://user-images.githubusercontent.com/47799652/88741198-1e7b0d80-d193-11ea-8e7e-0257022cda0b.png)


When clicking the link, its not doing anything on the testphone.

**Comment by djpnewton** [comment]
try redrat.blackpepper.co.nz and see what the difference is

**Comment by eoliveros** [comment]
the link showing is:
```
zap://3MsKcPckNDdCfvZJq2PGtDG7Dx8d9U8qMwF?amount=5699.00&asset=CgUrFtinLXEbJwJVjwwcppk4Vpz1nMmR3H5cQaDcUcfe&attachment=%7B%22invoice_id%22%3A%222050540003%22%2C%22message%22%3A%22RedRat%20Order%20payment%22%2C%22recipientName%22%3A%22TEST%20Red%20Rat%20%28OTS%29%20RedRat%20Website%22%7D 
```

**Comment by djpnewton** [comment]
ok try the link again

**Comment by eoliveros** [comment]
log a bug with the app not being redirected to the correct page.
