### ISSUE TITLE
We need to show more context to the user 

### ISSUE THREAD

**Issue by djpnewton** [zap-me/zap_bill_payment#17]
The user needs more information when:
 - the user receives an email
 - on the final invoice status page

The info we need is:
  - utility name
  - how much we are paying

**Comment by eoliveros** [comment]
added the amount in msg.body. Testing and waiting for the email to be sent.

**Comment by eoliveros** [comment]
not getting the email. will check.

**Comment by djpnewton** [comment]
is the email still failing?

**Comment by eoliveros** [comment]
just tested this. and i registered my personal email to see if I'll get the update. So far nothing.

**Comment by djpnewton** [comment]
I have added you as a collaborator (https://dashboard.heroku.com/apps/zap-bill-payment), check the logs when it sends the email

**Comment by eoliveros** [comment]
the zap-bll-payment in heroku is sending emails. Is there any way to get the one in caprover  to do that as well? I can't remember how to deploy to heroku and with my constant change and test, its better for me to get this environment working.

**Comment by djpnewton** [comment]
We dont have an instance in caprover yet, you can put one on if you want

**Comment by eoliveros** [comment]
I have this at the moment:

https://test-zap-bill-payment.caprover.acuerdo.dev

May need to update it though. As well as the config incase something is not matching.

**Comment by djpnewton** [comment]
Yes, you can deploy it to caprover for testing

**Comment by eoliveros** [comment]
trying to get this to email but, for some reason its not emailing. cant tell why its not emailing though.

**Comment by eoliveros** [comment]
checking the docker logs:

```
--SNIP--
connect sid: 6680d913ac71451191fa4e5d7cee6676
connect sid: 3586a20b3f96455e9983edd2e90395e7
watching address 3MwXqmVwLKF2ZKZ2g2HMcppe667TCLjnmtS for b0159ffc8caf3857
connect sid: 5bfa3949fc0f49db92e9615a3677c91a




--/SNIP--
```

There's nothing thats triggering the email?

**Comment by eoliveros** [comment]
ahhh, looks like its not fully uptodate.... pulling updates.

**Comment by eoliveros** [comment]
deployed and edited to get the amount:
![image](https://user-images.githubusercontent.com/47799652/92058414-6f5dd180-ede3-11ea-9f0a-6f402d860183.png)

Will need to cleanup the message though.

Also investigating on how to get the name of the utility in to the message as well.

**Comment by eoliveros** [comment]
Ok, with the changes to models.py and others, i got the msg to include the bank name as well:
![image](https://user-images.githubusercontent.com/47799652/92073728-8662ea80-ee08-11ea-928f-02d4195777e1.png)


so the name is also now included as well as the amount in $

**Comment by djpnewton** [comment]
Cool, now we need a PR to add that info to the invoice status page too

**Comment by eoliveros** [comment]
invoice status page? You mean this page?
![image](https://user-images.githubusercontent.com/47799652/92542112-04f1d900-f29c-11ea-9672-7eecc018e2f5.png)

The amount was already there. To get the utility_name to show up i had to edit the this as well to get the utility_name in the msg as well.

**Comment by djpnewton** [comment]
no the status page showed to the user, like when they follow the link in
the email

**Comment by eoliveros** [comment]
Like this?
![image](https://user-images.githubusercontent.com/47799652/92551476-2b227380-f2b2-11ea-9da1-3a3642f6c39d.png)

**Comment by djpnewton** [comment]
yeah but maybe in the main part next to the expiry

**Comment by eoliveros** [comment]
How about this:
![image](https://user-images.githubusercontent.com/47799652/92557209-ca019c80-f2bf-11ea-8b7c-1c63607d566a.png)

**Comment by djpnewton** [comment]
yep
