### ISSUE TITLE
Update DSL

### ISSUE THREAD

**Issue by djpnewton** [zap-me/zap_bill_payment#7]
Vodafone has four different bank accounts for NZ customers (A, B, C and D)

We should update our DSL to account for this.

I am thinking we:

- allow links in the utility description field so we can direct the user to more information (maybe we could automatically detect urls and automatically convert them into links that open in a new tab)
- allow utilities to have a dropdown list to choose a different set of bankaccount + field descriptions:
  - we could do this by adding a "parent/child utility" relationship and so if a utlitly has children then we allow the user to select the payment details for one of the children (possibly difficult to apply relationship from flask admin gui?)
  - we could also do this by changing fields_description to bank_descriptions and moving bank account into that, then we basically make it a list of bank descriptions and if there is more then one we allow the user to select which one

http://help.vodafone.co.nz/app/answers/detail/a_id/17702/~/pay-your-bill-using-internet-banking
http://help.vodafone.co.nz/app/answers/detail/a_id/29688/~/should-i-choose-vodafone-a%2C-b%2C-c-or-d%3F

**Comment by djpnewton** [comment]
fixed in 5f91155

**Comment by eoliveros** [comment]
Issue: If I try to create any new utility company getting the following error:
![image](https://user-images.githubusercontent.com/47799652/87744838-90bd2b00-c840-11ea-8f73-099184e9ab0d.png)

So trying to edit the one that's already there will fail as well. How to fix that.

**Comment by djpnewton** [comment]
@eoliveros  take a look at how the DSL has changed: https://github.com/zap-me/zap_bill_payment/blob/master/utility_form_dsl.md
